from collections.abc import Iterable, Mapping
from datetime import datetime
from typing import Generic, TypeVar, overload

_T = TypeVar("_T")

class _ILocIndexer(Generic[_T]):
    def __getitem__(self, index: int) -> _T: ...

class Series:
    iloc: _ILocIndexer[float]
    def __init__(self, data: Iterable[object] = ...) -> None: ...
    def __len__(self) -> int: ...

class DataFrame:
    columns: list[str]
    def __init__(self, data: Mapping[str, Iterable[object]] = ...) -> None: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, key: str) -> Series: ...
    @overload
    def __getitem__(self, key: list[str]) -> DataFrame: ...

class Timestamp:
    def __init__(self, value: int, *, unit: str, tz: str) -> None: ...
    def to_pydatetime(self) -> datetime: ...

def isna(value: object) -> bool: ...
def notna(value: object) -> bool: ...
