class _NamedValue:
    @property
    def name(self) -> str: ...

class _DecimalValue:
    def as_decimal(self) -> object: ...

class _OrderEvent:
    @property
    def client_order_id(self) -> object: ...
    @property
    def instrument_id(self) -> object: ...
    @property
    def venue_order_id(self) -> object | None: ...

class OrderAccepted(_OrderEvent): ...

class OrderFilled(_OrderEvent):
    @property
    def last_px(self) -> object: ...
    @property
    def last_qty(self) -> object: ...
    @property
    def order_side(self) -> _NamedValue: ...

class OrderCanceled(_OrderEvent):
    @property
    def order_side(self) -> _NamedValue: ...

class OrderRejected(_OrderEvent):
    @property
    def reason(self) -> object: ...

class OrderCancelRejected(_OrderEvent): ...

class _PositionEvent:
    @property
    def entry(self) -> _NamedValue: ...
    @property
    def instrument_id(self) -> object: ...
    @property
    def opening_order_id(self) -> object: ...
    @property
    def position_id(self) -> object: ...
    @property
    def quantity(self) -> object: ...

class PositionOpened(_PositionEvent): ...

class PositionClosed(_PositionEvent):
    @property
    def realized_pnl(self) -> _DecimalValue: ...
