from __future__ import annotations

from enum import StrEnum


class ArtifactVerificationCode(StrEnum):
    POLICY_ENVELOPE_INVALID = "POLICY_ENVELOPE_INVALID"
    POLICY_AUTHORITY_MISMATCH = "POLICY_AUTHORITY_MISMATCH"
    POLICY_SIGNATURE_INVALID = "POLICY_SIGNATURE_INVALID"
    POLICY_INVALID = "POLICY_INVALID"
    POLICY_NOT_YET_VALID = "POLICY_NOT_YET_VALID"
    POLICY_EXPIRED = "POLICY_EXPIRED"
    POLICY_BINDING_MISMATCH = "POLICY_BINDING_MISMATCH"
    TRUST_ROOT_DIGEST_MISMATCH = "TRUST_ROOT_DIGEST_MISMATCH"
    COMMAND_BINDING_INVALID = "COMMAND_BINDING_INVALID"
    BOM_DIGEST_MISMATCH = "BOM_DIGEST_MISMATCH"
    BOM_INVALID = "BOM_INVALID"
    BOM_NOT_CANONICAL = "BOM_NOT_CANONICAL"
    MEMBER_SET_MISMATCH = "MEMBER_SET_MISMATCH"
    MEMBER_NOT_REGULAR = "MEMBER_NOT_REGULAR"
    MEMBER_UNSTABLE = "MEMBER_UNSTABLE"
    MEMBER_SIZE_MISMATCH = "MEMBER_SIZE_MISMATCH"
    MEMBER_DIGEST_MISMATCH = "MEMBER_DIGEST_MISMATCH"
    SIGSTORE_VERIFIER_UNAVAILABLE = "SIGSTORE_VERIFIER_UNAVAILABLE"
    SIGSTORE_VERIFICATION_FAILED = "SIGSTORE_VERIFICATION_FAILED"
    SIGSTORE_EVIDENCE_MISMATCH = "SIGSTORE_EVIDENCE_MISMATCH"
    ARCHIVE_INVALID = "ARCHIVE_INVALID"
    ARCHIVE_UNSAFE = "ARCHIVE_UNSAFE"
    ARCHIVE_LIMIT_EXCEEDED = "ARCHIVE_LIMIT_EXCEEDED"
    ARCHIVE_CRC_MISMATCH = "ARCHIVE_CRC_MISMATCH"
    WHEEL_RECORD_INVALID = "WHEEL_RECORD_INVALID"
    ENTRY_POINT_INVALID = "ENTRY_POINT_INVALID"
    MANIFEST_INVALID = "MANIFEST_INVALID"


class ArtifactVerificationError(Exception):
    """Closed-code failure without artifact bytes, local paths, or secrets."""

    def __init__(self, code: ArtifactVerificationCode, detail: str) -> None:
        self.code = code
        self.detail = detail
        super().__init__(f"{code.value}: {detail}")
